import z from "zod";

const envSchema = z.object({
  NEXT_PUBLIC_BACKEND_ENDPOINT: z.string().min(1),
  NEXT_PUBLIC_LOGIN_ENDPOINT: z.string().min(1),
  NEXT_PUBLIC_SIGNUP_ENDPOINT: z.string().min(1),
  NEXT_PUBLIC_LOGOUT_ENDPOINT: z.string().min(1),
  NEXT_PUBLIC_PROFILE_ENDPOINT: z.string().min(1),
  NEXT_PUBLIC_REFRESH_ENDPOINT: z.string().min(1),
  NEXT_PUBLIC_VERIFY_ENDPOINT: z.string().min(1),
  NEXT_PUBLIC_ALL_PROJECT_ENDPOINT: z.string().min(1),
  NEXT_PUBLIC_CREATE_PROJECT_ENDPOINT: z.string().min(1),
  NEXT_PUBLIC_BASE_URL: z.string().min(1),
  NEXT_PUBLIC_DELETE_PROJECT: z.string().min(1),
  NEXT_PUBLIC_GET_PROJECT: z.string().min(1),
  NEXT_PUBLIC_GET_ANALYTICS: z.string().min(1),
  NEXT_PUBLIC_GET_DEPLOYMENTS: z.string().min(1),
  NEXT_PUBLIC_GET_DEPLOYMENT: z.string().min(1),
  NEXT_PUBLIC_PROJECT_ANALYTICS: z.string().min(1),
});

export const clientEnv = envSchema.parse({
  NEXT_PUBLIC_BACKEND_ENDPOINT: process.env.NEXT_PUBLIC_BACKEND_ENDPOINT,
  NEXT_PUBLIC_LOGIN_ENDPOINT: process.env.NEXT_PUBLIC_LOGIN_ENDPOINT,
  NEXT_PUBLIC_SIGNUP_ENDPOINT: process.env.NEXT_PUBLIC_SIGNUP_ENDPOINT,
  NEXT_PUBLIC_LOGOUT_ENDPOINT: process.env.NEXT_PUBLIC_LOGOUT_ENDPOINT,
  NEXT_PUBLIC_PROFILE_ENDPOINT: process.env.NEXT_PUBLIC_PROFILE_ENDPOINT,
  NEXT_PUBLIC_REFRESH_ENDPOINT: process.env.NEXT_PUBLIC_REFRESH_ENDPOINT,
  NEXT_PUBLIC_VERIFY_ENDPOINT: process.env.NEXT_PUBLIC_VERIFY_ENDPOINT,
  NEXT_PUBLIC_ALL_PROJECT_ENDPOINT:
    process.env.NEXT_PUBLIC_ALL_PROJECT_ENDPOINT,
  NEXT_PUBLIC_CREATE_PROJECT_ENDPOINT:
    process.env.NEXT_PUBLIC_CREATE_PROJECT_ENDPOINT,
  NEXT_PUBLIC_BASE_URL: process.env.NEXT_PUBLIC_BASE_URL,
  NEXT_PUBLIC_DELETE_PROJECT: process.env.NEXT_PUBLIC_DELETE_PROJECT,
  NEXT_PUBLIC_GET_PROJECT: process.env.NEXT_PUBLIC_GET_PROJECT,
  NEXT_PUBLIC_GET_ANALYTICS: process.env.NEXT_PUBLIC_GET_ANALYTICS,
  NEXT_PUBLIC_GET_DEPLOYMENTS: process.env.NEXT_PUBLIC_GET_DEPLOYMENTS,
  NEXT_PUBLIC_GET_DEPLOYMENT: process.env.NEXT_PUBLIC_GET_DEPLOYMENT,
  NEXT_PUBLIC_PROJECT_ANALYTICS: process.env.NEXT_PUBLIC_PROJECT_ANALYTICS,
});
