name: Go Worker

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

permissions:
  actions: write
  contents: read

jobs:
  worker:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    env:
      REDIS_URL: ${{ secrets.REDIS_URL }}
      DSN: ${{ secrets.DSN }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      GITHUB_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache: true

      - name: build worker
        run: go build -o worker

      - name: run worker
        run: ./worker
